name: CI
on: [push, pull_request]

env:
  RUST_BACKTRACE: full
  RUSTFLAGS: -D warnings
  CARGO_TERM_VERBOSE: true

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [stable, beta, nightly, macos]
        include:
          - build: stable
            os: ubuntu-20.04
            rust: stable
          - build: beta
            os: ubuntu-20.04
            rust: beta
          - build: nightly
            os: ubuntu-20.04
            rust: nightly
          - build: macos
            os: macos-latest
            rust: stable
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Install pstoedit (linux)
      if: matrix.os == 'ubuntu-20.04'
      run: |
           sudo apt-get update
           sudo apt-get install -y libpstoedit-dev
    - name: Install pstoedit (mac)
      if: matrix.os == 'macos-latest'
      run: brew install pstoedit
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
    - name: Build
      run: cargo build
    - name: Test
      run: cargo test
    - name: Build with smallvec feature
      run: cargo build --features smallvec
    - name: Test with smallvec feature
      run: cargo test --features smallvec

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Check clippy
      run: cargo clippy
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Check documentation
      run: cargo doc --no-deps
